### ISSUE TITLE
Validación de propuesta

### ISSUE THREAD

**Issue by Rosa218** [SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-servitlax#2]
[propuesta de valor.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-servitlax/files/8150574/propuesta.de.valor.pdf)

**Comment by Abraham890** [comment]
Calificación:16 puntos 
Falta mejor un poco más el trabajo

**Comment by josealfredo79** [comment]
Bien hecho y revisado

**Comment by josealfredo79** [comment]
esta bien hecho y revisado
